-- Schema for the Postgres store. Applied idempotently at startup.
-- Product ids are BIGINT identities, serialized as strings in the API
-- (matching the OpenAPI example id "10").
--
-- Indexing: every current products query is served by the PRIMARY KEY's
-- implicit unique B-tree — point lookups (id = $1 → Index Scan), the order
-- path (id = ANY($1) → Bitmap Index Scan), ordered listing (ORDER BY id),
-- and the cache fingerprint (max(id) → backward index scan). No secondary
-- indexes are declared because no query needs one yet: unused indexes are
-- pure write amplification. The first real candidate is (category) if a
-- filtered listing endpoint ever ships.

CREATE TABLE IF NOT EXISTS products (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT             NOT NULL CHECK (length(name) BETWEEN 1 AND 200),
    price      DOUBLE PRECISION NOT NULL CHECK (price > 0),
    category   TEXT             NOT NULL CHECK (length(category) BETWEEN 1 AND 100),
    created_at TIMESTAMPTZ      NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
    id          UUID        PRIMARY KEY,
    coupon_code TEXT        NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_items (
    order_id   UUID   NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    position   INT    NOT NULL,
    product_id BIGINT NOT NULL REFERENCES products (id),
    quantity   INT    NOT NULL CHECK (quantity > 0),
    PRIMARY KEY (order_id, position)
);

CREATE INDEX IF NOT EXISTS order_items_product_idx ON order_items (product_id);
